include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_linter

dart_code_linter:
  metrics:
    cyclomatic-complexity: 10
    number-of-parameters: 4
    maximum-nesting-level: 5
    halstead-volume: 100
  rules:
    - avoid-dynamic
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - prefer-trailing-comma
    - no-equal-then-else